# Generated by Django 4.0.4 on 2022-05-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_countrydata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydata',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
