# Generated by Django 4.0.4 on 2022-06-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tbl_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_employee',
            old_name='exprience',
            new_name='experience',
        ),
    ]
