# Generated by Django 4.0.4 on 2022-06-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_checkboxdata_alter_summarized_dataset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxdata',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
